sudo: false
language: node_js
node_js:
  - "8"
  - "6"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - yarn lint
  - yarn test -- --ci
  - yarn codecov
