sudo: false
language: node_js
node_js:
  - "8"
  - "6"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
  directories:
    - "node_modules"
before_script:
  - 'if [[ -n "$TRAVIS_TAG" ]] && [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then yarn run create-github-release; fi'
script:
  - yarn lint
  - yarn test -- --ci
after_success: yarn website
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $CONVENTIONAL_GITHUB_RELEASER_TOKEN
  local_dir: examples/dist
  on:
    branch: master
    node: "8"
